version: '3'

services: 

    mysql-development:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: asd123
            MYSQL_DATABASE: taboo
        ports:
            - "3306:3306"
